CREATE TABLE Person (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name varchar(100) NOT NULL UNIQUE,
    birth_year int NOT NULL CHECK (birth_year > 1900)
);

CREATE TABLE Book (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id int REFERENCES Person(id) ON DELETE SET NULL,
    name varchar(100) NOT NULL,
    author varchar(100) NOT NULL,
    creation_year int NOT NULL
);